# This file was automatically generated by APIMATIC v2.0 on 04/15/2016

# Require controllers
#require '/var/lib/gems/2.2.0/gems/pepipost_apiv_10-1.0.0/lib/pepipost_apiv_10/controllers/email_controller.rb'
require 'pepipost_sdk_ruby/controllers/email_controller.rb'

module PepipostSdkRuby
  class PepipostSdkRubyClient
    # Singleton access to email controller
    # @return [EmailController] Returns the controller instance
    def email
      EmailController.instance
    end

  end
end
