# pepipost_gem
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PepipostGem
  # Attachments Model.
  class Attachments < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :file_content

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :file_name

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['file_content'] = 'fileContent'
      @_hash['file_name'] = 'fileName'
      @_hash
    end

    def initialize(file_content = nil,
                   file_name = nil)
      @file_content = file_content
      @file_name = file_name
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      file_content = hash['fileContent']
      file_name = hash['fileName']

      # Create object from extracted values.
      Attachments.new(file_content,
                      file_name)
    end
  end
end
