# pepipost_gem
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PepipostGem
  # Attribute Model.
  class Attribute < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :myname

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :age

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['myname'] = 'myname'
      @_hash['age'] = 'age'
      @_hash
    end

    def initialize(myname = nil,
                   age = nil)
      @myname = myname
      @age = age
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      myname = hash['myname']
      age = hash['age']

      # Create object from extracted values.
      Attribute.new(myname,
                    age)
    end
  end
end
