# pepipost_gem
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PepipostGem
  # From Model.
  class Attributes
    # TODO: Write general description for this method

    def initialize(attributes = nil)
      @attributes = APIHelper.json_deserialize(attributes)
    end

    def get_attributes()
      return @attributes
    end

  end
end
