# pepipost_gem
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PepipostGem
  # From Model.
  class From < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :from_email

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :from_name

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['from_email'] = 'fromEmail'
      @_hash['from_name'] = 'fromName'
      @_hash
    end

    def initialize(from_email = nil,
                   from_name = nil)
      @from_email = from_email
      @from_name = from_name
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      from_email = hash['fromEmail']
      from_name = hash['fromName']

      # Create object from extracted values.
      From.new(from_email,
               from_name)
    end
  end
end
