# pepipost_gem
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PepipostGem
  # SendEmailError Model.
  class SendEmailError < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :error_message

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :error_code

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['error_message'] = 'error_message'
      @_hash['error_code'] = 'error_code'
      @_hash
    end

    def initialize(error_message = nil,
                   error_code = nil)
      @error_message = error_message
      @error_code = error_code
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      error_message = hash['error_message']
      error_code = hash['error_code']

      # Create object from extracted values.
      SendEmailError.new(error_message,
                         error_code)
    end
  end
end
