# pepipost_gem
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PepipostGem
  # Response of the email
  class SendEmailResponse < BaseModel
    # TODO: Write general description for this method
    # @return [Object]
    attr_accessor :data

    # TODO: Write general description for this method
    # @return [String]
    attr_reader :message

    # TODO: Write general description for this method
    # @return [SendEmailError]
    attr_accessor :error_info

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['data'] = 'data'
      @_hash['message'] = 'message'
      @_hash['error_info'] = 'error_info'
      @_hash
    end

    def initialize(data = nil,
                   message = nil,
                   error_info = nil)
      @data = data
      @message = message
      @error_info = error_info
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      data = hash['data']
      message = hash['message']
      error_info = SendEmailError.from_hash(hash['error_info']) if
        hash['error_info']

      # Create object from extracted values.
      SendEmailResponse.new(data,
                            message,
                            error_info)
    end
  end
end
