# pepipost_gem
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module PepipostGem
  # From Model.
  class Xheaders
    # TODO: Write general description for this method

    def initialize(xheaders = nil)
      @xheaders = APIHelper.json_deserialize(xheaders)
    end

    def get_xheaders()
      return @xheaders
    end

  end
end
