# This file was automatically generated by APIMATIC v2.0 on 04/15/2016

module PepipostApiv10
  class Configuration
    # The base Uri for API calls
    @base_uri = 'https://api.pepipost.com'

    # create the getters and setters
    class << self
      attr_accessor :base_uri

    end
  end
end
