# pepipost
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module Pepipost
  # Utility class for custom header authorization.
  class CustomHeaderAuth
    # Add custom authentication to the request.
    # @param [HttpRequest] The HttpRequest object to which authentication will
    # be added.
    def self.apply(http_request)
      http_request.add_header('api_key', Configuration.api_key)
    end
  end
end
