# This file was automatically generated by APIMATIC v2.0 on 04/15/2016
require 'openssl'
require 'json'
require 'unirest'

# APIMATIC Helper Files
require 'pepipost_apiv_10/api_helper.rb'
require 'pepipost_apiv_10/api_exception.rb'
require 'pepipost_apiv_10/configuration.rb'
require 'pepipost_apiv_10/pepipost_apiv_10_client.rb'

# Controllers
require 'pepipost_apiv_10/controllers/email_controller.rb'

# Models
require 'pepipost_apiv_10/models/attributes.rb'
require 'pepipost_apiv_10/models/files.rb'
require 'pepipost_apiv_10/models/emailv_1.rb'
require 'pepipost_apiv_10/models/email_details.rb'
require 'pepipost_apiv_10/models/settings.rb'
