# pepipost_gem
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
require 'json'
require 'faraday'
require 'certifi'
require 'logging'

require_relative 'pepipost_gem/api_helper.rb'
require_relative 'pepipost_gem/pepipost_gem_client.rb'

# Http
require_relative 'pepipost_gem/http/http_call_back.rb'
require_relative 'pepipost_gem/http/http_client.rb'
require_relative 'pepipost_gem/http/http_method_enum.rb'
require_relative 'pepipost_gem/http/http_request.rb'
require_relative 'pepipost_gem/http/http_response.rb'
require_relative 'pepipost_gem/http/http_context.rb'
require_relative 'pepipost_gem/http/faraday_client.rb'

# Models
require_relative 'pepipost_gem/models/base_model.rb'
require_relative 'pepipost_gem/models/from.rb'
require_relative 'pepipost_gem/models/email_body_attachments.rb'
require_relative 'pepipost_gem/models/attribute.rb'
require_relative 'pepipost_gem/models/attachments.rb'
require_relative 'pepipost_gem/models/personalizations.rb'
require_relative 'pepipost_gem/models/email_body.rb'
require_relative 'pepipost_gem/models/settings.rb'
require_relative 'pepipost_gem/models/send_email_error.rb'
require_relative 'pepipost_gem/models/send_email_response.rb'

# Exceptions
require_relative 'pepipost_gem/exceptions/api_exception.rb'

require_relative 'pepipost_gem/configuration.rb'

# Controllers
require_relative 'pepipost_gem/controllers/base_controller.rb'
require_relative 'pepipost_gem/controllers/email_controller.rb'
