# This file was automatically generated by APIMATIC v2.0 on 04/15/2016
require 'openssl'
require 'json'
require 'unirest'

# APIMATIC Helper Files
require 'pepipost_sdk_ruby/api_helper.rb'
require 'pepipost_sdk_ruby/api_exception.rb'
require 'pepipost_sdk_ruby/configuration.rb'
require 'pepipost_sdk_ruby/pepipost_sdk_ruby_client.rb'

# Controllers
require 'pepipost_sdk_ruby/controllers/email_controller.rb'

# Models
require 'pepipost_sdk_ruby/models/attributes.rb'
require 'pepipost_sdk_ruby/models/files.rb'
require 'pepipost_sdk_ruby/models/emailv_1.rb'
require 'pepipost_sdk_ruby/models/email_details.rb'
require 'pepipost_sdk_ruby/models/settings.rb'
