# pepipost
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

require 'date'
require 'json'
require 'faraday'
require 'certifi'
require 'logging'

require_relative 'pepipost/api_helper.rb'
require_relative 'pepipost/pepipost_client.rb'

# Http
require_relative 'pepipost/http/http_call_back.rb'
require_relative 'pepipost/http/http_client.rb'
require_relative 'pepipost/http/http_method_enum.rb'
require_relative 'pepipost/http/http_request.rb'
require_relative 'pepipost/http/http_response.rb'
require_relative 'pepipost/http/http_context.rb'
require_relative 'pepipost/http/faraday_client.rb'
require_relative 'pepipost/http/auth/custom_header_auth.rb'

# Models
require_relative 'pepipost/models/base_model.rb'
require_relative 'pepipost/models/from.rb'
require_relative 'pepipost/models/settings.rb'
require_relative 'pepipost/models/content.rb'
require_relative 'pepipost/models/attachments.rb'
require_relative 'pepipost/models/email_struct.rb'
require_relative 'pepipost/models/personalizations.rb'
require_relative 'pepipost/models/send.rb'
require_relative 'pepipost/models/type_enum.rb'

# Exceptions
require_relative 'pepipost/exceptions/api_exception.rb'

require_relative 'pepipost/configuration.rb'

# Controllers
require_relative 'pepipost/controllers/base_controller.rb'
require_relative 'pepipost/controllers/send_controller.rb'
