# pepipost
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

require 'date'
require 'json'
require 'faraday'
require 'certifi'
require 'logging'

require_relative 'pepipost/api_helper.rb'
require_relative 'pepipost/pepipost_client.rb'

# Http
require_relative 'pepipost/http/http_call_back.rb'
require_relative 'pepipost/http/http_client.rb'
require_relative 'pepipost/http/http_method_enum.rb'
require_relative 'pepipost/http/http_request.rb'
require_relative 'pepipost/http/http_response.rb'
require_relative 'pepipost/http/http_context.rb'
require_relative 'pepipost/http/faraday_client.rb'
require_relative 'pepipost/http/auth/custom_header_auth.rb'

# Models
require_relative 'pepipost/models/base_model.rb'
require_relative 'pepipost/models/content.rb'
require_relative 'pepipost/models/personalizations.rb'
require_relative 'pepipost/models/from.rb'
require_relative 'pepipost/models/settings.rb'
require_relative 'pepipost/models/email_struct.rb'
require_relative 'pepipost/models/attachments.rb'
require_relative 'pepipost/models/send.rb'
require_relative 'pepipost/models/domain_struct.rb'
require_relative 'pepipost/models/deletedomain.rb'
require_relative 'pepipost/models/addemailordomainto_suppressionlist.rb'
require_relative 'pepipost/models/removeemailordomainto_suppressionlist.rb'
require_relative 'pepipost/models/createsubaccount.rb'
require_relative 'pepipost/models/updatesubaccount.rb'
require_relative 'pepipost/models/update_credisofsubaccount.rb'
require_relative 'pepipost/models/updaterecurring_credisofsubaccount.rb'
require_relative 'pepipost/models/deletesubacoount.rb'
require_relative 'pepipost/models/enableordisablesubacoount.rb'
require_relative 'pepipost/models/type_enum.rb'
require_relative 'pepipost/models/action_enum.rb'
require_relative 'pepipost/models/aggregated_by_enum.rb'
require_relative 'pepipost/models/events_enum.rb'
require_relative 'pepipost/models/sort_enum.rb'
require_relative 'pepipost/models/timeperiod_enum.rb'

# Exceptions
require_relative 'pepipost/exceptions/api_exception.rb'

require_relative 'pepipost/configuration.rb'

# Controllers
require_relative 'pepipost/controllers/base_controller.rb'
require_relative 'pepipost/controllers/mail_send_controller.rb'
require_relative 'pepipost/controllers/events_controller.rb'
require_relative 'pepipost/controllers/stats_controller.rb'
require_relative 'pepipost/controllers/subaccounts_controller.rb'
require_relative 'pepipost/controllers/subaccounts_delete_controller.rb'
require_relative 'pepipost/controllers/subaccounts_get_sub_accounts' \
                 '_controller.rb'
require_relative 'pepipost/controllers/subaccounts_getcreditddetails' \
                 '_controller.rb'
require_relative 'pepipost/controllers/setrecurringcreditddetails_controller.rb'
require_relative 'pepipost/controllers/subaccounts_setsubaccountcredit' \
                 '_controller.rb'
require_relative 'pepipost/controllers/subaccounts_update_subaccount' \
                 '_controller.rb'
require_relative 'pepipost/controllers/subaccounts_create_subaccount' \
                 '_controller.rb'
require_relative 'pepipost/controllers/suppression_controller.rb'
require_relative 'pepipost/controllers/domain_delete_controller.rb'
require_relative 'pepipost/controllers/domain_get_domains_controller.rb'
require_relative 'pepipost/controllers/template_controller.rb'
require_relative 'pepipost/controllers/domain_controller.rb'
