# pepipost
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module Pepipost
  # Indicate the action (add or subtract) to be taken.Allowed values increase,
  # decrease
  class ActionEnum
    ACTION_ENUM = [
      # TODO: Write general description for INCREASE
      INCREASE = 'increase'.freeze,

      # TODO: Write general description for DECREASE
      DECREASE = 'decrease'.freeze
    ].freeze
  end
end
