# pepipost
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module Pepipost
  # Add Suppression modal
  class AddEmailOrDomainToSuppressionList < BaseModel
    # Add the domain to be suppressed here. We will not deliver emails to
    # recipients email addresses with this domain.<br>\nComma separate the
    # values to suppress multiple domains..
    # @return [String]
    attr_accessor :domain

    # Add an email address to be suppressed here. We will not deliver emails to
    # this email address.<br>\nComma separate the values to suppress multiple
    # email addresses
    # @return [String]
    attr_accessor :email

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['domain'] = 'domain'
      @_hash['email'] = 'email'
      @_hash
    end

    def initialize(domain = nil,
                   email = nil)
      @domain = domain
      @email = email
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      domain = hash['domain']
      email = hash['email']

      # Create object from extracted values.
      AddEmailOrDomainToSuppressionList.new(domain,
                                            email)
    end
  end
end
