# pepipost
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module Pepipost
  # aggregated_by.
  class AggregatedByEnum
    AGGREGATED_BY_ENUM = [
      # TODO: Write general description for DAY
      DAY = 'day'.freeze,

      # TODO: Write general description for WEEK
      WEEK = 'week'.freeze,

      # TODO: Write general description for MONTH
      MONTH = 'month'.freeze
    ].freeze
  end
end
