# pepipost
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module Pepipost
  # Attachments
  class Attachments < BaseModel
    # Base64 encoded value of the attached file
    # @return [String]
    attr_accessor :content

    # filename of attachments
    # @return [String]
    attr_accessor :name

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['content'] = 'content'
      @_hash['name'] = 'name'
      @_hash
    end

    def initialize(content = nil,
                   name = nil)
      @content = content
      @name = name
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      content = hash['content']
      name = hash['name']

      # Create object from extracted values.
      Attachments.new(content,
                      name)
    end
  end
end
