# pepipost
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module Pepipost
  # AMP, HTML should be provided
  class Content < BaseModel
    # TODO: Write general description for this method
    # @return [TypeEnum]
    attr_accessor :type

    # HTML content to be sent in your email
    # @return [String]
    attr_accessor :value

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['type'] = 'type'
      @_hash['value'] = 'value'
      @_hash
    end

    def initialize(type = nil,
                   value = nil)
      @type = type
      @value = value
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      type = hash['type']
      value = hash['value']

      # Create object from extracted values.
      Content.new(type,
                  value)
    end
  end
end
