# pepipost
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module Pepipost
  # CreateSubaccount modal
  class Createsubaccount < BaseModel
    # provide a username for the subaccount
    # @return [String]
    attr_accessor :username

    # email address to be registered with the account.
    # @return [String]
    attr_accessor :email

    # You can opt to set the password for the subaccount.\nIf set as 1, please
    # provide a value in password parameter.\nIf set as 0, the email
    # confirmation link will act as a password reset link.
    # @return [String]
    attr_accessor :setpassword

    # It is required to pass this value, if setpassword is set as 1.\nThe
    # password must comprise minimum of 8 characters and include one uppercase
    # character, one lowercase character, one numeric character.
    # @return [String]
    attr_accessor :password

    # Allowed values one_time_credit or unlimited by default, all subaccounts
    # are created with credit type as unlimited.
    # @return [String]
    attr_accessor :credit_type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['username'] = 'username'
      @_hash['email'] = 'email'
      @_hash['setpassword'] = 'setpassword'
      @_hash['password'] = 'password'
      @_hash['credit_type'] = 'credit_type'
      @_hash
    end

    def initialize(username = nil,
                   email = nil,
                   setpassword = nil,
                   password = nil,
                   credit_type = nil)
      @username = username
      @email = email
      @setpassword = setpassword
      @password = password
      @credit_type = credit_type
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      username = hash['username']
      email = hash['email']
      setpassword = hash['setpassword']
      password = hash['password']
      credit_type = hash['credit_type']

      # Create object from extracted values.
      Createsubaccount.new(username,
                           email,
                           setpassword,
                           password,
                           credit_type)
    end
  end
end
