# pepipost
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module Pepipost
  # delete domain modal
  class DeleteDomain < BaseModel
    # Name of the domain
    # @return [String]
    attr_accessor :domain

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['domain'] = 'domain'
      @_hash
    end

    def initialize(domain = nil)
      @domain = domain
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      domain = hash['domain']

      # Create object from extracted values.
      DeleteDomain.new(domain)
    end
  end
end
