# pepipost
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module Pepipost
  # Deletesubaccount modal
  class Deletesubacoount < BaseModel
    # The username of the subaccount
    # @return [String]
    attr_accessor :username

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['username'] = 'username'
      @_hash
    end

    def initialize(username = nil)
      @username = username
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      username = hash['username']

      # Create object from extracted values.
      Deletesubacoount.new(username)
    end
  end
end
