# pepipost
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module Pepipost
  # Domain Modal
  class DomainStruct < BaseModel
    # The domain you wish to include in the 'From' header of your emails.
    # @return [String]
    attr_accessor :domain

    # The subdomain which will be used for tracking opens, clicks and
    # unsubscribe
    # @return [String]
    attr_accessor :envelope_name

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['domain'] = 'domain'
      @_hash['envelope_name'] = 'envelopeName'
      @_hash
    end

    def initialize(domain = nil,
                   envelope_name = nil)
      @domain = domain
      @envelope_name = envelope_name
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      domain = hash['domain']
      envelope_name = hash['envelopeName']

      # Create object from extracted values.
      DomainStruct.new(domain,
                       envelope_name)
    end
  end
end
