# pepipost
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module Pepipost
  # EnableDisablesubaccount modal
  class Enableordisablesubacoount < BaseModel
    # The username of the subaccount
    # @return [String]
    attr_accessor :username

    # Flag to indicate whether the subaccount should be enabled or disabled.
    # @return [Boolean]
    attr_accessor :disabled

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['username'] = 'username'
      @_hash['disabled'] = 'disabled'
      @_hash
    end

    def initialize(username = nil,
                   disabled = nil)
      @username = username
      @disabled = disabled
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      username = hash['username']
      disabled = hash['disabled']

      # Create object from extracted values.
      Enableordisablesubacoount.new(username,
                                    disabled)
    end
  end
end
