# pepipost
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module Pepipost
  # events.
  class EventsEnum
    EVENTS_ENUM = [
      # TODO: Write general description for PROCESSED
      PROCESSED = 'processed'.freeze,

      # TODO: Write general description for SENT
      SENT = 'sent'.freeze,

      # TODO: Write general description for OPEN
      OPEN = 'open'.freeze,

      # TODO: Write general description for CLICK
      CLICK = 'click'.freeze,

      # TODO: Write general description for UNSUBSCRIBE
      UNSUBSCRIBE = 'unsubscribe'.freeze,

      # TODO: Write general description for BOUNCE
      BOUNCE = 'bounce'.freeze,

      # TODO: Write general description for SOFTBOUNCE
      SOFTBOUNCE = 'softbounce'.freeze,

      # TODO: Write general description for SPAM
      SPAM = 'spam'.freeze,

      # TODO: Write general description for INVALID
      INVALID = 'invalid'.freeze,

      # TODO: Write general description for DROPPED
      DROPPED = 'dropped'.freeze,

      # TODO: Write general description for HARDBOUNCE
      HARDBOUNCE = 'hardbounce'.freeze
    ].freeze
  end
end
