# pepipost
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module Pepipost
  # Email address representing the sender of the mail
  class From < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :email

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['email'] = 'email'
      @_hash['name'] = 'name'
      @_hash
    end

    def initialize(email = nil,
                   name = nil)
      @email = email
      @name = name
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      email = hash['email']
      name = hash['name']

      # Create object from extracted values.
      From.new(email,
               name)
    end
  end
end
