# pepipost
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module Pepipost
  # Remove Suppression modal
  class RemoveemailordomaintoSuppressionlist < BaseModel
    # List one or more recipient domains to be removed from the suppression list
    # here. <br>\nComma separate the values to suppress multiple recipient
    # domains.
    # @return [String]
    attr_accessor :domain

    # List one or more email addresses to be removed from the suppression list
    # here. <br>\nComma separate the values to suppress multiple email
    # addresses.
    # @return [String]
    attr_accessor :email

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['domain'] = 'domain'
      @_hash['email'] = 'email'
      @_hash
    end

    def initialize(domain = nil,
                   email = nil)
      @domain = domain
      @email = email
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      domain = hash['domain']
      email = hash['email']

      # Create object from extracted values.
      RemoveemailordomaintoSuppressionlist.new(domain,
                                               email)
    end
  end
end
