# pepipost
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module Pepipost
  # Settings Model.
  class Settings < BaseModel
    # enable or disable footer
    # @return [Boolean]
    attr_accessor :footer

    # enable or disable click tracking
    # @return [Boolean]
    attr_accessor :click_track

    # enable or disable open tracking
    # @return [Boolean]
    attr_accessor :open_track

    # enable or disable unsubscribe tracking
    # @return [Boolean]
    attr_accessor :unsubscribe_track

    # enable or disable unsubscribe tracking
    # @return [Boolean]
    attr_accessor :hepf

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['footer'] = 'footer'
      @_hash['click_track'] = 'click_track'
      @_hash['open_track'] = 'open_track'
      @_hash['unsubscribe_track'] = 'unsubscribe_track'
      @_hash['hepf'] = 'hepf'
      @_hash
    end

    def initialize(footer = nil,
                   click_track = nil,
                   open_track = nil,
                   unsubscribe_track = nil,
                   hepf = nil)
      @footer = footer
      @click_track = click_track
      @open_track = open_track
      @unsubscribe_track = unsubscribe_track
      @hepf = hepf
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      footer = hash['footer']
      click_track = hash['click_track']
      open_track = hash['open_track']
      unsubscribe_track = hash['unsubscribe_track']
      hepf = hash['hepf']

      # Create object from extracted values.
      Settings.new(footer,
                   click_track,
                   open_track,
                   unsubscribe_track,
                   hepf)
    end
  end
end
