# pepipost
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module Pepipost
  # sort.
  class SortEnum
    SORT_ENUM = [
      # TODO: Write general description for ASC
      ASC = 'asc'.freeze,

      # TODO: Write general description for DESC
      DESC = 'desc'.freeze
    ].freeze
  end
end
