# pepipost
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module Pepipost
  # The periodic \n\nAllowed values  \"daily\", \"weekly\", \"monhtly\"
  class TimeperiodEnum
    TIMEPERIOD_ENUM = [
      # TODO: Write general description for DAILY
      DAILY = 'daily'.freeze,

      # TODO: Write general description for WEEKLY
      WEEKLY = 'weekly'.freeze,

      # TODO: Write general description for MONHTLY
      MONHTLY = 'monhtly'.freeze
    ].freeze
  end
end
