# pepipost
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module Pepipost
  # Type.
  class TypeEnum
    TYPE_ENUM = [
      # TODO: Write general description for AMP
      AMP = 'amp'.freeze,

      # TODO: Write general description for HTML
      HTML = 'html'.freeze
    ].freeze
  end
end
