# pepipost
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module Pepipost
  # UpdateCreditaccount modal
  class UpdateCredisOfSubaccount < BaseModel
    # The username of the subaccount
    # @return [String]
    attr_accessor :username

    # Indicate the action (add or subtract) to be taken.Allowed values increase,
    # decrease
    # @return [ActionEnum]
    attr_accessor :action

    # Amount of credits
    # @return [Integer]
    attr_accessor :amount

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['username'] = 'username'
      @_hash['action'] = 'action'
      @_hash['amount'] = 'amount'
      @_hash
    end

    def initialize(username = nil,
                   action = nil,
                   amount = nil)
      @username = username
      @action = action
      @amount = amount
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      username = hash['username']
      action = hash['action']
      amount = hash['amount']

      # Create object from extracted values.
      UpdateCredisOfSubaccount.new(username,
                                   action,
                                   amount)
    end
  end
end
