# pepipost
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module Pepipost
  # SendController
  class SendController < BaseController
    @instance = SendController.new

    class << self
      attr_accessor :instance
    end

    def instance
      self.class.instance
    end

    # The endpoint send is used to generate the request to pepipost server for
    # sending an email to recipients.
    # @param [Send] body Required parameter: New mail request will be
    # generated
    # @return List of String response from the API call
    def create_generate_the_mail_send_request(body)
      # Prepare query url.
      _path_url = '/send'
      _query_builder = Configuration.get_base_uri(
        Configuration::Server::SERVER1
      )
      _query_builder << _path_url
      _query_url = APIHelper.clean_url _query_builder
      # Prepare headers.
      _headers = {
        'accept' => 'application/json',
        'content-type' => 'application/json; charset=utf-8'
      }
      # Prepare and execute HttpRequest.
      _request = @http_client.post(
        _query_url,
        headers: _headers,
        parameters: body.to_json
      )
      CustomHeaderAuth.apply(_request)
      _context = execute_request(_request)
      # Validate response against endpoint and global error codes.
      if _context.response.status_code == 405
        raise APIException.new(
          'Invalid input',
          _context
        )
      end
      validate_response(_context)
      # Return appropriate response type.
      decoded = APIHelper.json_deserialize(_context.response.raw_body)
      decoded
    end
  end
end
