# pepipost
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module Pepipost
  # SuppressionController
  class SuppressionController < BaseController
    @instance = SuppressionController.new

    class << self
      attr_accessor :instance
    end

    def instance
      self.class.instance
    end

    # This API allows you to suppress an email address and block any future
    # email delivery attempts on this email address.
    # @param [AddemailordomaintoSuppressionlist] body Required parameter: add
    # email or domain to suppression list
    # @return Object response from the API call
    def adddomainoremailtosuppressionlist(body)
      # Prepare query url.
      _path_url = '/suppression'
      _query_builder = Configuration.base_uri.dup
      _query_builder << _path_url
      _query_url = APIHelper.clean_url _query_builder
      # Prepare headers.
      _headers = {
        'content-type' => 'application/json; charset=utf-8'
      }
      # Prepare and execute HttpRequest.
      _request = @http_client.post(
        _query_url,
        headers: _headers,
        parameters: body.to_json
      )
      CustomHeaderAuth.apply(_request)
      _context = execute_request(_request)
      # Validate response against endpoint and global error codes.
      if _context.response.status_code == 400
        raise APIException.new(
          'API Response',
          _context
        )
      elsif _context.response.status_code == 401
        raise APIException.new(
          'API Response',
          _context
        )
      elsif _context.response.status_code == 403
        raise APIException.new(
          'API Response',
          _context
        )
      elsif _context.response.status_code == 405
        raise APIException.new(
          'Invalid input',
          _context
        )
      end
      validate_response(_context)
      # Return appropriate response type.
      _context.response.raw_body
    end

    # Use this API to remove an email address or a recipient domain from the
    # suppression list. You can remove multiple email addresses and recipient
    # domains together by passing them as values & separating them using commas
    # as shown below.
    # @param [RemoveemailordomaintoSuppressionlist] body Required parameter:
    # remove email or domain to suppression list
    # @return Object response from the API call
    def removedomainoremailtosuppressionlist(body)
      # Prepare query url.
      _path_url = '/suppression'
      _query_builder = Configuration.base_uri.dup
      _query_builder << _path_url
      _query_url = APIHelper.clean_url _query_builder
      # Prepare headers.
      _headers = {
        'content-type' => 'application/json; charset=utf-8'
      }
      # Prepare and execute HttpRequest.
      _request = @http_client.delete(
        _query_url,
        headers: _headers,
        parameters: body.to_json
      )
      CustomHeaderAuth.apply(_request)
      _context = execute_request(_request)
      # Validate response against endpoint and global error codes.
      if _context.response.status_code == 400
        raise APIException.new(
          'API Response',
          _context
        )
      elsif _context.response.status_code == 401
        raise APIException.new(
          'API Response',
          _context
        )
      elsif _context.response.status_code == 403
        raise APIException.new(
          'API Response',
          _context
        )
      elsif _context.response.status_code == 405
        raise APIException.new(
          'Invalid input',
          _context
        )
      end
      validate_response(_context)
      # Return appropriate response type.
      _context.response.raw_body
    end
  end
end
