# pepipost
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module Pepipost
  #  pepipost client class.
  class PepipostClient
    # Singleton access to mail_send controller.
    # @return [MailSendController] Returns the controller instance.
    def mail_send
      MailSendController.instance
    end

    # Singleton access to events controller.
    # @return [EventsController] Returns the controller instance.
    def events
      EventsController.instance
    end

    # Singleton access to stats controller.
    # @return [StatsController] Returns the controller instance.
    def stats
      StatsController.instance
    end

    # Singleton access to subaccounts controller.
    # @return [SubaccountsController] Returns the controller instance.
    def subaccounts
      SubaccountsController.instance
    end

    # Singleton access to subaccounts_delete controller.
    # @return [SubaccountsDeleteController] Returns the controller instance.
    def subaccounts_delete
      SubaccountsDeleteController.instance
    end

    # Singleton access to subaccounts_get_sub_accounts controller.
    # @return [SubaccountsGetSubAccountsController] Returns the controller instance.
    def subaccounts_get_sub_accounts
      SubaccountsGetSubAccountsController.instance
    end

    # Singleton access to subaccounts_getcreditddetails controller.
    # @return [SubaccountsGetcreditddetailsController] Returns the controller instance.
    def subaccounts_getcreditddetails
      SubaccountsGetcreditddetailsController.instance
    end

    # Singleton access to setrecurringcreditddetails controller.
    # @return [SetrecurringcreditddetailsController] Returns the controller instance.
    def setrecurringcreditddetails
      SetrecurringcreditddetailsController.instance
    end

    # Singleton access to subaccounts_setsubaccountcredit controller.
    # @return [SubaccountsSetsubaccountcreditController] Returns the controller instance.
    def subaccounts_setsubaccountcredit
      SubaccountsSetsubaccountcreditController.instance
    end

    # Singleton access to subaccounts_update_subaccount controller.
    # @return [SubaccountsUpdateSubaccountController] Returns the controller instance.
    def subaccounts_update_subaccount
      SubaccountsUpdateSubaccountController.instance
    end

    # Singleton access to subaccounts_create_subaccount controller.
    # @return [SubaccountsCreateSubaccountController] Returns the controller instance.
    def subaccounts_create_subaccount
      SubaccountsCreateSubaccountController.instance
    end

    # Singleton access to suppression controller.
    # @return [SuppressionController] Returns the controller instance.
    def suppression
      SuppressionController.instance
    end

    # Singleton access to domain_delete controller.
    # @return [DomainDeleteController] Returns the controller instance.
    def domain_delete
      DomainDeleteController.instance
    end

    # Singleton access to domain_get_domains controller.
    # @return [DomainGetDomainsController] Returns the controller instance.
    def domain_get_domains
      DomainGetDomainsController.instance
    end

    # Singleton access to template controller.
    # @return [TemplateController] Returns the controller instance.
    def template
      TemplateController.instance
    end

    # Singleton access to domain controller.
    # @return [DomainController] Returns the controller instance.
    def domain
      DomainController.instance
    end

    # Returns the configuration class for easy access.
    # @return [Configuration] Returns the actual configuration class.
    def config
      Configuration
    end

    # Initializer with authentication and configuration parameters.
    def initialize(api_key: nil)
      Configuration.api_key = api_key if
        api_key
    end
  end
end
